# Generated by Django 4.2.3 on 2023-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisments',
            name='titel',
            field=models.CharField(max_length=50, verbose_name='заголовок'),
        ),
        migrations.AlterModelTable(
            name='advertisments',
            table='advertisements',
        ),
    ]
